package com.bizhub.model.services.common.DB;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * A Connection wrapper that makes {@link #close()} a no-op.
 * <p>
 * This allows the shared singleton connection from {@link MyDatabase} to be used
 * safely inside try-with-resources blocks (which the investment module does)
 * without killing the connection for the rest of the application.
 * <p>
 * Every other method delegates directly to the underlying real connection.
 */
class NonClosingConnectionWrapper implements Connection {

    private final Connection real;

    NonClosingConnectionWrapper(Connection real) {
        this.real = real;
    }

    /** No-op — the shared connection must stay open. */
    @Override public void close() { /* intentionally empty */ }

    // ── Validity / state — delegate to real ──────────────────────────────────

    @Override public boolean isClosed() throws SQLException { return real.isClosed(); }
    @Override public boolean isValid(int timeout) throws SQLException { return real.isValid(timeout); }

    // ── Statement factories ──────────────────────────────────────────────────

    @Override public Statement createStatement() throws SQLException { return real.createStatement(); }
    @Override public PreparedStatement prepareStatement(String sql) throws SQLException { return real.prepareStatement(sql); }
    @Override public CallableStatement prepareCall(String sql) throws SQLException { return real.prepareCall(sql); }

    @Override public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException { return real.createStatement(resultSetType, resultSetConcurrency); }
    @Override public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException { return real.prepareStatement(sql, resultSetType, resultSetConcurrency); }
    @Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException { return real.prepareCall(sql, resultSetType, resultSetConcurrency); }

    @Override public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException { return real.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability); }
    @Override public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException { return real.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability); }
    @Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException { return real.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability); }

    @Override public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException { return real.prepareStatement(sql, autoGeneratedKeys); }
    @Override public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException { return real.prepareStatement(sql, columnIndexes); }
    @Override public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException { return real.prepareStatement(sql, columnNames); }

    // ── Transaction control ──────────────────────────────────────────────────

    @Override public void setAutoCommit(boolean autoCommit) throws SQLException { real.setAutoCommit(autoCommit); }
    @Override public boolean getAutoCommit() throws SQLException { return real.getAutoCommit(); }
    @Override public void commit() throws SQLException { real.commit(); }
    @Override public void rollback() throws SQLException { real.rollback(); }
    @Override public void rollback(Savepoint savepoint) throws SQLException { real.rollback(savepoint); }
    @Override public Savepoint setSavepoint() throws SQLException { return real.setSavepoint(); }
    @Override public Savepoint setSavepoint(String name) throws SQLException { return real.setSavepoint(name); }
    @Override public void releaseSavepoint(Savepoint savepoint) throws SQLException { real.releaseSavepoint(savepoint); }
    @Override public void setTransactionIsolation(int level) throws SQLException { real.setTransactionIsolation(level); }
    @Override public int getTransactionIsolation() throws SQLException { return real.getTransactionIsolation(); }

    // ── Metadata ─────────────────────────────────────────────────────────────

    @Override public DatabaseMetaData getMetaData() throws SQLException { return real.getMetaData(); }
    @Override public String getCatalog() throws SQLException { return real.getCatalog(); }
    @Override public void setCatalog(String catalog) throws SQLException { real.setCatalog(catalog); }
    @Override public String getSchema() throws SQLException { return real.getSchema(); }
    @Override public void setSchema(String schema) throws SQLException { real.setSchema(schema); }
    @Override public String nativeSQL(String sql) throws SQLException { return real.nativeSQL(sql); }
    @Override public SQLWarning getWarnings() throws SQLException { return real.getWarnings(); }
    @Override public void clearWarnings() throws SQLException { real.clearWarnings(); }

    // ── Type / holdability / client info ──────────────────────────────────────

    @Override public void setReadOnly(boolean readOnly) throws SQLException { real.setReadOnly(readOnly); }
    @Override public boolean isReadOnly() throws SQLException { return real.isReadOnly(); }
    @Override public void setHoldability(int holdability) throws SQLException { real.setHoldability(holdability); }
    @Override public int getHoldability() throws SQLException { return real.getHoldability(); }
    @Override public Map<String, Class<?>> getTypeMap() throws SQLException { return real.getTypeMap(); }
    @Override public void setTypeMap(Map<String, Class<?>> map) throws SQLException { real.setTypeMap(map); }

    @Override public Properties getClientInfo() throws SQLException { return real.getClientInfo(); }
    @Override public String getClientInfo(String name) throws SQLException { return real.getClientInfo(name); }
    @Override public void setClientInfo(Properties properties) throws SQLClientInfoException { real.setClientInfo(properties); }
    @Override public void setClientInfo(String name, String value) throws SQLClientInfoException { real.setClientInfo(name, value); }

    // ── LOB / Array / Struct factories ────────────────────────────────────────

    @Override public Clob createClob() throws SQLException { return real.createClob(); }
    @Override public Blob createBlob() throws SQLException { return real.createBlob(); }
    @Override public NClob createNClob() throws SQLException { return real.createNClob(); }
    @Override public SQLXML createSQLXML() throws SQLException { return real.createSQLXML(); }
    @Override public Array createArrayOf(String typeName, Object[] elements) throws SQLException { return real.createArrayOf(typeName, elements); }
    @Override public Struct createStruct(String typeName, Object[] attributes) throws SQLException { return real.createStruct(typeName, attributes); }

    // ── Network / abort ──────────────────────────────────────────────────────

    @Override public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException { real.setNetworkTimeout(executor, milliseconds); }
    @Override public int getNetworkTimeout() throws SQLException { return real.getNetworkTimeout(); }
    @Override public void abort(Executor executor) throws SQLException { real.abort(executor); }

    // ── Wrapper ──────────────────────────────────────────────────────────────

    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return real.isWrapperFor(iface); }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { return real.unwrap(iface); }
}

